# Generated by Django 5.0.6 on 2024-09-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clinet_type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('client_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('client_phone', models.CharField(max_length=10)),
                ('client_email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('client_address', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('client_status', models.CharField(blank=True, default='pending', max_length=100, null=True)),
                ('created_on', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('updated_on', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
