# Generated by Django 5.0.6 on 2024-09-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, default='Active', max_length=30, null=True),
        ),
    ]
