# Generated by Django 5.0.6 on 2024-09-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_employee_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
    ]
