# Generated by Django 5.0.6 on 2024-09-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_client_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_phone', models.CharField(max_length=10)),
                ('client_message', models.TextField(blank=True, default='', null=True)),
                ('updated_on', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
