# Generated by Django 5.0.6 on 2024-09-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_client_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_history',
            name='client_next_followup_date',
            field=models.CharField(default='', max_length=30),
        ),
    ]
