# Generated by Django 5.1.1 on 2024-09-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_client_history_client_next_followup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_next_followup_date',
            field=models.CharField(default='', max_length=30),
        ),
    ]
