# Generated by Django 5.1.2 on 2024-11-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_rename_status_employee_empstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='emp_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='category',
            field=models.CharField(blank=True, default='Telesales', max_length=30, null=True),
        ),
    ]
