# Generated by Django 5.1.2 on 2024-11-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='allocator',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
